public class MillionaireQuestions {
    String questions [] = {"What is the capital of France?",
    "Which critically acclaimed and heavily influential Atlanta Rapper is currently being tried for A RICO case?",
    "Which fast-food chain was sued for false advertisement in 2023 and lost?",
    "Which of these 4 US presidents are made up?",
    "In which ocean is the Great Barrier Reef located?",
    "Who is known as the 'Queen of Pop'?",
    "Which planet is known as the 'Red Planet'?",
    "What is the largest mammal in the world?",
    "Which famous scientist developed the theory of relativity?",
    "What is the currency of Japan?",
    "Which element has the chemical symbol 'O'?",
    "Who wrote 'Romeo and Juliet'?",
    "What is the largest desert in the world?",
    "Which famous painting features a woman with an enigmatic smile?",
    "Which ancient wonder of the world was located in Egypt?",
    "What is the smallest prime number?",
    "Which novel features the character Jay Gatsby?",
    "In what year did Christopher Columbus first reach the Americas?",
    "Which gas do plants absorb during photosynthesis?",
    "Who is the author of the Harry Potter series?",
    "What is the capital city of Australia?",
    "Which famous scientist discovered the laws of motion?",
    "What is the largest mammal in North America?",
    "Which element has the chemical symbol 'Fe'?",
    "What is the main ingredient in guacamole?",
    "In what year did the United States declare its independence?",
    "Which mountain range spans seven countries in Southern Europe?",
    "Who wrote 'The Canterbury Tales'?",
    "What is the largest moon in our solar system?",
    "Which planet is known as the 'Morning Star' or 'Evening Star'?"};

    String questionAnswers [] = {"A. Paris B. London C. Rome D. Berlin A",
        "A. YNW Melly B. Young Thug C. Kanye West D. Kay Flock B",
        "A. McDonald's B. Taco Bell C. Burger King D. Tim Horton B",
        "A. Zachary Taylor B. Chester A. Arthur C. Calvin Coolidge D. Jefferson Steele D",
        "A. Pacific B. Atlantic C. Indian D. Southern A",
        "A. Madonna B. Beyoncé C. Taylor Swift D. Adele A",
        "A. Mars B. Venus C. Jupiter D. Saturn A",
        "A. Elephant B. Blue Whale C. Giraffe D. Hippopotamus B",
        "A. Isaac Newton B. Albert Einstein C. Galileo Galilei D. Stephen Hawking B",
        "A. Yen B. Won C. Ringgit D. Baht A",
        "A. Oxygen" , "B. Gold", "C. Silver", "D. Mercury", "A",
        "A. Charles Dickens" , "B. William Shakespeare", "C. Jane Austen", "D. Mark Twain", "B",
        "A. Sahara" , "B. Gobi", "C. Antarctic", "D. Atacama", "C",
        "A. The Starry Night" , "B. Guernica", "C. The Scream", "D. Mona Lisa", "D",
        "A. Hanging Gardens of Babylon" , "B. Great Pyramid of Giza", "C. Temple of Artemis", "D. Statue of Zeus at Olympia", "B",
        "A. 0" , "B. 1", "C. 2", "D. 3", "C",
        "A. Pride and Prejudice" , "B. The Great Gatsby", "C. To Kill a Mockingbird", "D. 1984", "B",
        "A. 1492" , "B. 1505", "C. 1607", "D. 1776", "A",
        "A. Oxygen" , "B. Nitrogen", "C. Carbon Dioxide", "D. Hydrogen", "C",
        "A. J.K. Rowling" , "B. George R.R. Martin", "C. Stephen King", "D. Suzanne Collins", "A",
        "A. Sydney" , "B. Melbourne", "C. Canberra", "D. Brisbane", "C",
        "A. Isaac Newton" , "B. Albert Einstein", "C. Galileo Galilei", "D. Marie Curie", "A",
        "A. Grizzly Bear" , "B. Bison", "C. Moose", "D. Blue Whale", "D",
        "A. Iron" , "B. Gold", "C. Silver", "D. Mercury", "A",
        "A. Tomato" , "B. Avocado", "C. Onion", "D. Lime", "B",
        "A. 1620" , "B. 1776", "C. 1812", "D. 1945", "B",
        "A. Rocky Mountains" , "B. Alps", "C. Andes", "D. Himalayas", "B",
        "A. Geoffrey Chaucer" , "B. William Shakespeare", "C. Jane Austen", "D. Charles Dickens", "A",
        "A. Io" , "B. Titan", "C. Ganymede", "D. Phobos", "C",
        "A. Venus" , "B. Mars", "C. Jupiter", "D. Saturn", "A"};

    public String getQuestion(){
        int random = (int) (Math.random() * 30);
        return questions[random];
    }
}
